### ISSUE TITLE
Bioconda Package

### ISSUE THREAD

**Issue by apeltzer** [23andMe/yhaplo#10]
Would it be ok to bundle this in a bioconda package for other scientific users to use it more easily?

**Comment by dpoznik** [comment]
Thanks for asking. I've not used Bioconda before, so I have a couple questions.
1. Is yhaplo's [license](https://github.com/23andMe/yhaplo/blob/master/LICENSE.txt), which precludes commercial use, compatible with Bioconda's requirements? We could not list it in PyPI due to the non-commercial use restriction.
2. How would updates to this GitHub repo propagate to the Bioconda package?

**Comment by apeltzer** [comment]
Hi @dpoznik !

1. https://bioconda.github.io/guidelines.html#packages-appropriate-for-bioconda there is no such limitation as long as you'd be happy with the package being distributed via Bioconda for everyone to download it. Your license can be listed in the `meta.yaml` and will be shown to potential users, with a link to this release/repository here so I think if that's okay for you this will be fine.
2. We can open a PR with the updated recipe on bioconda, merge it in and the new version will appear on the bioconda channel. If you don't want to do it yourself, I'm happy to package it once now and future updates should be easy. Some people even automate this using some continuous integration service, that should be possible too.

**Comment by dpoznik** [comment]
Thanks for all the information. I think we'd prefer to maintain it independently at this time.
