### ISSUE TITLE
ERROR. Attempted to access haplogroup before assigned:

### ISSUE THREAD

**Issue by rozaimirazali** [23andMe/yhaplo#12]
Hello. What does this error mean?

------------------------------------------------------------------------
Reading genotype data...
    QGP_MALE_onlyGT.vcf.gz

ERROR. Attempted to access haplogroup before assigned: 0100066181_S5_L005

This is my command:

> callHaplogroups.py --input QGP_MALE_onlyGT.vcf.gz --ancDerCounts --haplogroupPaths --derSNPs --derSNPsDetail --ancSNPs --anc
> SNPsDetail --hgGenos hg

**Comment by dpoznik** [comment]
Rozaimi, thanks for writing in again.

Short answer: For normal usage, the `--hgGenos` option is unnecessary, so I suggest omitting it.

Longer answer: The option can provide a useful view of your genotype data at SNPs associated with a specified branch of the Y-chromosome tree, if that's something you're interested in. There are two reasons it didn't work for you:
1. You need to specify which haplogroup you want to investigate. For example, if you want to look at the root of the Q haplogroup, you would do something like this:
`callHaplogroups.py --input data/1000Y.subset.genos.txt --hgGenos Q`
I've updated the metavariable to be `haplogroup` rather than `hg` to make this more explicit.
2. The option was not working for SNP-major input, but it is fixed in version 1.0.18.
