### ISSUE TITLE
Yhaplo analysis on UK Biobank data

### ISSUE THREAD

**Issue by jielab** [23andMe/yhaplo#40]
Dear David:

Please refer to my post at PLINK users group:
https://groups.google.com/g/plink2-users/c/Xvt895jb48w

It seems that **there is no readl ChrY data from the UK Biobank genotype dataset**, and therefore there is no way to run Yhaplo program on it, correct?

I run the following command on the UK Biobank ChrXY male data anyway: **yhaplo -i chrXY-males.vcf.gz -o jie**. 

There is **NO error message, and I got the output files** as listed at this link https://github.com/jielab/001/tree/master/jie. 

I was expecting to get a phylogentic tree dataset for all the male samples who have genotype data, but none of the output .awk file included such information.

So, please kindly advise how to run yhaplo on UK Biobank genetic data. 

Thank you & best regards,
Jie

**Comment by teepean** [comment]
How did you originally create this "pfile chrXY"?

**Comment by jielab** [comment]
I originally used **gfetch** to download the UKB raw genotype data and then used p**link2 --bed --bim --fam --make-bed** to generate the ChrXY data.

Best regards,
Jie

**Comment by teepean** [comment]
Does the original .bim file have chrY or chromosome numbered 24? Both represent chromosome Y.

**Comment by jielab** [comment]
Please see the screenshot below.

The gentyped data only has 1357 variants and all are labelled XY.
The imputed data has 45907 variants. All except 1 are labelled XY.

![image](https://github.com/23andMe/yhaplo/assets/26947455/bedbca97-348d-4762-baf5-30634bfd0bee)

Best regards,
Jie

**Comment by teepean** [comment]
I don't have access to UKBB so I am not sure how gfetch works. Could you show the command you downloaded the data?

**Comment by jielab** [comment]
The UKBB genotype data is NOT downloadable anymore. gfetch is simply a UKBB provided tool to download big data, just like FTP. 

Anyway, the full list of SNPs (including those for chromosome X, XY) were downloadable from this link https://biobank.ndph.ox.ac.uk/showcase/ukb/auxdata/ukb_snp_bim.tar, as written on this page https://biobank.ndph.ox.ac.uk/showcase/refer.cgi?id=1963.

For your convenience, I also posted chrY.bim and chrXY.bim at my Github https://github.com/jielab/001/tree/master/jie.

Can you please take a look at this SNP file and kindly let me know if Yhaplo could infer phylogeny from this data?

Thanks!

Jie

**Comment by teepean** [comment]
The tar archive has ukb_snp_chrY_v2.bim that has only 691 Y snps. I am not sure that is enough.

**Comment by jielab** [comment]
But they also have chrXY. Also, the imputed data has tens of thousands of SNPs for ChrX and ChrXY. 

It would be great if you guys are interested in applying Yhaplo to UKBB data.

Best regards,
Jie

**Comment by dpoznik** [comment]
@jielab, thanks for your interest in Yhaplo. As indicated in the PLINK forum you linked, "XY" refers to the [pseudoautosomal region](https://en.wikipedia.org/wiki/Pseudoautosomal_region) of the X & Y chromosomes. Variants in these regions are not informative for Y-chromosome haplogroups, as these regions recombine between the X and the Y, hence "XY". To place individual Y chromosomes on the Y-chromosome phylogeny, you'll need data from the non-recombining portion of the Y chromosome (NRY), as indicated by the first error message you encountered:
```
ValueError: VCF must include exactly one contig with a label in: ['24', 'Y', 'chrY']. Observed: {'X', 'XY'}
```
Changing the name of the contig from "XY" to "Y" silences the error message but doesn't address the underlying issue. In doing so, you're telling Yhaplo that the data in the input file are from the NRY. Yhaplo then doesn't recognize any of the variants in the file, because they are not Y-chromosome variants. When presented with no data, Yhaplo assigns each haplotype to the root of the phylogeneny, "A". That explains the output files you generated.

I have not worked with UKBB data, so I don't know if they've called or released Y-chromsome data. But if they have, I imagine Yhaplo should run just fine on it. Let me know if you run into any issues.

**Comment by dpoznik** [comment]
I'll go ahead and close the issue for now. Feel free to reopen if something comes up.
